package verify

import (
	"fmt"

	"github.com/monyratha/migration-verify/internal/report"
)

// compareVersions compares the full version history of every key.
//
// Version IDs are generated by the server and cannot be preserved by any
// S3-level migration tool, so they are NOT compared. Instead the ordered
// sequence of versions per key (oldest -> newest) is compared on:
// delete-marker flag, size and ETag. This catches missing versions, extra
// versions, re-ordered histories and missing delete markers.
func compareVersions(src, tgt map[string][]*objInfo) (diffs []report.VersionDiff, srcTotal, tgtTotal int) {
	keys := map[string]bool{}
	for k := range src {
		keys[k] = true
	}
	for k := range tgt {
		keys[k] = true
	}
	for key := range keys {
		sv, tv := src[key], tgt[key]
		srcTotal += len(sv)
		tgtTotal += len(tv)
		d := report.VersionDiff{Key: key, SourceVersion: len(sv), TargetVersion: len(tv)}
		for _, v := range sv {
			if v.IsDeleteMarker {
				d.SourceDeleteM++
			}
		}
		for _, v := range tv {
			if v.IsDeleteMarker {
				d.TargetDeleteM++
			}
		}
		if len(sv) != len(tv) {
			d.Reasons = append(d.Reasons, fmt.Sprintf("version count %d != %d", len(sv), len(tv)))
		}
		if d.SourceDeleteM != d.TargetDeleteM {
			d.Reasons = append(d.Reasons, fmt.Sprintf("delete markers %d != %d", d.SourceDeleteM, d.TargetDeleteM))
		}
		if len(sv) == len(tv) {
			for i := range sv {
				a, b := sv[i], tv[i]
				if a.IsDeleteMarker != b.IsDeleteMarker {
					d.Reasons = append(d.Reasons, fmt.Sprintf("version[%d] delete-marker %v != %v", i, a.IsDeleteMarker, b.IsDeleteMarker))
					continue
				}
				if a.IsDeleteMarker {
					continue
				}
				if a.Size != b.Size {
					d.Reasons = append(d.Reasons, fmt.Sprintf("version[%d] size %d != %d", i, a.Size, b.Size))
				}
				if compareETags(a, b) == etagMismatch {
					d.Reasons = append(d.Reasons, fmt.Sprintf("version[%d] etag %s != %s", i, a.ETag, b.ETag))
				}
			}
		}
		if len(d.Reasons) > 0 {
			diffs = append(diffs, d)
		}
	}
	return diffs, srcTotal, tgtTotal
}
