#!/usr/bin/env sh
# Writes chorus/docker-compose/s3-credentials.yaml from environment variables.
#
# This is the file the Chorus worker reads to learn about the two storages.
# Generating it means you never edit anything inside the chorus/ clone: put
# your values in .env and run 'make chorus-config'.
#
# The Makefile loads .env and exports these variables. To run this script by
# hand, load .env yourself first:
#
#   set -a; . ./.env; set +a; scripts/render-s3-credentials.sh
set -eu

OUT="${OUT:-chorus/docker-compose/s3-credentials.yaml}"

SOURCE_URL="${SOURCE_URL:-http://minio-a:9000}"
SOURCE_ACCESS_KEY="${SOURCE_ACCESS_KEY:-minioadmin}"
SOURCE_SECRET_KEY="${SOURCE_SECRET_KEY:-minioadmin}"
SOURCE_PROVIDER="${SOURCE_PROVIDER:-Minio}"
SOURCE_REGION="${SOURCE_REGION:-}"

TARGET_URL="${TARGET_URL:-http://minio-b:9000}"
TARGET_ACCESS_KEY="${TARGET_ACCESS_KEY:-minioadmin}"
TARGET_SECRET_KEY="${TARGET_SECRET_KEY:-minioadmin}"
TARGET_PROVIDER="${TARGET_PROVIDER:-Minio}"
TARGET_REGION="${TARGET_REGION:-}"

CHORUS_USER="${CHORUS_USER:-user1}"

# isSecure follows the URL scheme, so there is one less thing to get wrong.
secure_for() {
  case "$1" in
    https://*) echo true ;;
    *)         echo false ;;
  esac
}

# A URL the worker cannot resolve is the most common mistake, and the worker
# only reports it later as a health-check failure.
warn_localhost() {
  case "$2" in
    *//localhost*|*//127.0.0.1*|*//[::1]*)
      echo "warning: $1 is $2 — inside the worker container that means the" >&2
      echo "         container itself, not your machine. Use a hostname or IP" >&2
      echo "         the container can reach (host.docker.internal on Mac)." >&2
      ;;
  esac
}

warn_localhost SOURCE_URL "$SOURCE_URL"
warn_localhost TARGET_URL "$TARGET_URL"

[ -d "$(dirname "$OUT")" ] || {
  echo "error: $(dirname "$OUT") does not exist. Run 'make chorus-clone' first." >&2
  exit 1
}

cat > "$OUT" <<YAML
# Generated by scripts/render-s3-credentials.sh — do not edit.
# Change .env in the repository root, then run 'make chorus-config'.
storage:
  main: main
  storages:
    main:
      type: S3
      address: "$SOURCE_URL"
      credentials:
        $CHORUS_USER:
          accessKeyID: $SOURCE_ACCESS_KEY
          secretAccessKey: $SOURCE_SECRET_KEY
      provider: $SOURCE_PROVIDER
      healthCheckInterval: 10s
      httpTimeout: 1m
      isSecure: $(secure_for "$SOURCE_URL")
      defaultRegion: "$SOURCE_REGION"
      rateLimit:
        enable: true
        rpm: 600
    follower:
      type: S3
      address: "$TARGET_URL"
      credentials:
        $CHORUS_USER:
          accessKeyID: $TARGET_ACCESS_KEY
          secretAccessKey: $TARGET_SECRET_KEY
      provider: $TARGET_PROVIDER
      healthCheckInterval: 10s
      httpTimeout: 1m
      isSecure: $(secure_for "$TARGET_URL")
      defaultRegion: "$TARGET_REGION"
      rateLimit:
        enable: true
        rpm: 600
YAML

echo "wrote $OUT"
echo "  main     $SOURCE_URL ($SOURCE_PROVIDER)"
echo "  follower $TARGET_URL ($TARGET_PROVIDER)"
